name: web3wallet
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  kakao_flutter_sdk: ^1.9.5
  kakao_flutter_sdk_user: ^1.9.5
  url_launcher: ^6.1.5
  local_auth: ^2.1.6
  pdfx: ^2.3.0
  internet_file: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: GmarketSansBold
      fonts:
        - asset: assets/fonts/GmarketSansBold.otf
    - family: GmarketSansLight
      fonts:
        - asset: assets/fonts/GmarketSansLight.otf
    - family: GmarketSansMedium
      fonts:
        - asset: assets/fonts/GmarketSansMedium.otf
    - family: KNUTRUTH
      fonts:
        - asset: assets/fonts/KNU_TRUTH.otf
